import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {PoochBox, PoochText} from "../src/ui-components";
import {PoochTextVariant} from "../src/ui-components/text";
import {SizesEnum} from "../src/settings/sizes";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <PoochBox background="orange" padding={{ x: SizesEnum.ExtraLarge, y: SizesEnum.Large }}>
          <PoochText variant={PoochTextVariant.Title1}>Hello hooman!</PoochText>
          <PoochText variant={PoochTextVariant.Title3}>Woof, woof…</PoochText>
      </PoochBox>
      </main>
    </div>
  )
}

export default Home
